image: debian:bullseye

before_script: 
    - apt-get update -qq  
    - apt-get install -y gpg curl  
    - curl https://mirror.sron.nl/sron.key | gpg --dearmor > /usr/share/keyrings/sron-archive-keyring.gpg  
    - apt-key add /usr/share/keyrings/sron-archive-keyring.gpg  
    - echo "deb http://mirror.sron.nl/debian bullseye main contrib non-free" > /etc/apt/sources.list  
    - echo "deb http://mirror.sron.nl/sron-bullseye bullseye main" >> /etc/apt/sources.list  
    - echo "deb http://mirror.sron.nl/security bullseye-security main contrib non-free" >> /etc/apt/sources.list  
    - apt-get update -qq  - apt-get install -y python3 python3-numpy python3-sphinx python3-pip texlive-base
    - pip3 install --no-cache-dir sphinx-sitemap

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the manual..."
    - make html
    - echo "Compile complete."

