image: python:3

before_script: 
    - pip install --no-cache-dir --upgrade pip
    - pip install --no-cache-dir sphinx
    - pip install --no-cache-dir sphinx-sitemap

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the manual..."
    - make html
    - echo "Compile complete."

